### ISSUE TITLE
Final review for TOP master and X2 FA

### ISSUE THREAD

**Issue by chloecwh** [TWUOnline/inno101-q#1]
- Cloned quarto to TWUOnline
- here's a [live link](https://twuonline.github.io/inno101-q/)
- [X2 shell](https://learn.twu.ca/course/view.php?id=36689)
- [TOP master shell](https://learn.twu.ca/course/view.php?id=36687&section=1#tabs-tree-start)

**Comment by chloecwh** [comment]
Hi @kmarjanovic I checked your reviewed work and have notice that the bulletin list syntax has been simplified 

From this screenshot: The three space tabs are no longer needed for Quarto
![Screenshot 2024-10-28 at 2 45 57 PM](https://github.com/user-attachments/assets/916a923f-2811-4a2f-b718-aa2df66194a2)

I have added a line of space between heading of questions to consider or notes
![Screenshot 2024-10-28 at 3 19 57 PM](https://github.com/user-attachments/assets/391158df-201e-4cd0-b0a1-c6a4186985ee)

It has been rendered and fixed!

**Comment by chloecwh** [comment]
https://github.com/TWUOnline/bug-tracking/issues/1046

**Comment by kmarjanovic** [comment]
Thanks so much @chloecwh !!

**Comment by kmarjanovic** [comment]
@chloecwh just wanted to double check on the bulleted list issue.  There were several of these that I needed to fix.  Just one space is needed, correct?

**Comment by chloecwh** [comment]
@kmarjanovic no space after the sentence is needed (:
